# config/augment/default.yaml
version_base: 1.3
enable: true

# Neue Flags für einzelne Augmentations
use_resizedcrop: true
use_hflip:        true
use_vflip:        true
use_rotation:     false
rotation_degree:  15        # Grad für RandomRotation
use_colorjitter:  false
cj_brightness:    0.3
cj_contrast:      0.3
cj_saturation:    0.3
cj_hue:           0.1
use_perspective:  false
perspective_distortion_scale: 0.2
perspective_p:    0.5
use_blur:         false
blur_kernel:      [3,7]
blur_sigma:       [0.1,3.0]
use_erasing:      false
erasing_p:        0.5
erasing_scale:    [0.02,0.2]
erasing_ratio:    [0.3,3.3]